## Ejercicio 1:
##### Dado un tensor de 2 dimensiones, intercambia las filas 2 y 4.



In [2]:
import numpy as np

In [3]:
# Tensor de ejemplo
tensor = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Intercambiar filas 2 y 4
tensor[[1, 3]] = tensor[[3, 1]]

print(tensor)

[[ 1  2  3]
 [10 11 12]
 [ 7  8  9]
 [ 4  5  6]]


## Ejercicio 2:
### Dado un tensor de 3 dimensiones, obtén el subtensor formado por las filas 2 y 3 de la matriz 1 y las columnas 1 y 3 de la matriz 2.


In [6]:
# Tensor de ejemplo
tensor = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],

                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],

                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

# Obtener el subtensor deseado
subtensor = tensor[0, 1:3, [0, 2]]

print(subtensor)

[[4 7]
 [6 9]]


## Ejercicio 3:
### Dado un tensor de 4 dimensiones, selecciona los elementos en la posición (0, 1, 1, 2) y (2, 3, 0, 1).

In [15]:

# Tensor de ejemplo
tensor = np.array([[[[1, 2],
                     [3, 4]],

                    [[5, 6],
                     [7, 8]]],

                   [[[9, 10],
                     [11, 12]],

                    [[13, 14],
                     [15, 16]]]])

# Selección de elementos
# elementos = tensor[[0, 2], 1, 1, [2, 1]]
elementos = tensor[0,1,1,1]
elemento2 = tensor[1,1,0,1]

print(elementos)
print(elemento2)

8
14
